AllCops:
  Exclude:
    - 'db/*'
    - 'node_modules/**/*'
    - 'app/assets/**/*'
    - 'app/javascript/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
